name: Scrape & Update Class Data

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install jsdom node-fetch@2

      - name: Run script
        run: node index.js

            - name: Commit updated classData.json
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          git add classData.json
          git diff --cached --quiet || git commit -m "Update class data"
          git push
